const samples = {
	JSON: '{\n  "name": "Ricky",\n  "age": 27\n}',
	"Go Struct":
		'type AutoGenerated struct {\n  Name string `json:"name"`\n  Age  int    `json:"age"`\n}',
	YAML: "name: Ricky\nage: 27",
	TOML: 'name = "Ricky"\nage = 27',
	"JSON Schema": `{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "integer" }
  },
  "required": ["name", "age"]
}`,
};

const transforms = {
	"JSON|Go Struct": {
		run: (text) => invokeWasm(window.jsonToGoStruct, text),
	},
	"Go Struct|JSON": {
		run: (text) => invokeWasm(window.goStructToJSON, text),
	},
	"YAML|Go Struct": {
		run: (text) => invokeWasm(window.yamlToGoStruct, text),
	},
	"Go Struct|YAML": {
		run: (text) => invokeWasm(window.goStructToYAML, text),
	},
	"JSON|YAML": {
		run: (text) => invokeWasm(window.jsonToYAML, text),
	},
	"YAML|JSON": {
		run: (text) => invokeWasm(window.yamlToJSON, text),
	},
	"JSON|TOML": {
		run: (text) => invokeWasm(window.jsonToTOML, text),
	},
	"TOML|JSON": {
		run: (text) => invokeWasm(window.tomlToJSON, text),
	},
	"TOML|Go Struct": {
		run: (text) => invokeWasm(window.tomlToGoStruct, text),
	},
	"Go Struct|TOML": {
		run: (text) => invokeWasm(window.goStructToTOML, text),
	},
	"JSON|JSON Schema": {
		run: (text) => invokeWasm(window.jsonToSchema, text),
	},
	"JSON Schema|JSON": {
		run: (text) => invokeWasm(window.schemaToJSON, text),
	},
	"Go Struct|JSON Schema": {
		run: (text) => invokeWasm(window.goStructToSchema, text),
	},
	"JSON Schema|Go Struct": {
		run: (text) => invokeWasm(window.schemaToGoStruct, text),
	},
	"YAML|TOML": {
		run: (text) => runPipeline(
			[window.yamlToJSON, window.jsonToTOML],
			text,
		),
	},
	"TOML|YAML": {
		run: (text) => runPipeline(
			[window.tomlToJSON, window.jsonToYAML],
			text,
		),
	},
	"YAML|JSON Schema": {
		run: (text) =>
			runPipeline([window.yamlToJSON, window.jsonToSchema], text),
	},
	"JSON Schema|YAML": {
		run: (text) =>
			runPipeline([window.schemaToJSON, window.jsonToYAML], text),
	},
	"TOML|JSON Schema": {
		run: (text) =>
			runPipeline([window.tomlToJSON, window.jsonToSchema], text),
	},
	"JSON Schema|TOML": {
		run: (text) =>
			runPipeline([window.schemaToJSON, window.jsonToTOML], text),
	},
};

const elements = {};
let currentKey = "JSON|Go Struct";
let wasmReady = false;
let debounceTimer = null;
let wasmInitPromise = null;

document.addEventListener("DOMContentLoaded", () => {
	cacheElements();
	bindEvents();
	ensureMode();
	loadWasm();
});

function cacheElements() {
	elements.from = document.getElementById("fromSelect");
	elements.to = document.getElementById("toSelect");
	elements.swap = document.getElementById("swap");
	elements.input = document.getElementById("input");
	elements.output = document.getElementById("output");
	elements.copy = document.getElementById("copy");
	elements.clear = document.getElementById("clear");
	elements.status = document.getElementById("status");
	elements.inputLabel = document.getElementById("inputLabel");
	elements.outputLabel = document.getElementById("outputLabel");
}

function bindEvents() {
	elements.from.addEventListener("change", onModeChange);
	elements.to.addEventListener("change", onModeChange);
	elements.swap.addEventListener("click", onSwap);
	elements.copy.addEventListener("click", copyOutput);
	elements.clear.addEventListener("click", clearAll);
	elements.input.addEventListener("input", () => scheduleConvert());
	window.addEventListener("keydown", handleHotkeys);
}

function onModeChange() {
	if (!ensureMode()) {
		setStatus("這個組合尚未支援", true);
	}
}

function onSwap() {
	const from = elements.from.value;
	const to = elements.to.value;
	elements.from.value = to;
	elements.to.value = from;
	onModeChange();
}

function ensureMode() {
	const key = `${elements.from.value}|${elements.to.value}`;
	if (!transforms[key]) {
		currentKey = null;
		return false;
	}
	currentKey = key;
	const [from, to] = key.split("|");
	elements.inputLabel.textContent = from;
	elements.outputLabel.textContent = to;
	elements.input.placeholder = samples[from] || "";
	scheduleConvert(true);
	return true;
}

function scheduleConvert(immediate = false) {
	if (immediate) {
		convert();
		return;
	}
	clearTimeout(debounceTimer);
	debounceTimer = setTimeout(() => convert(), 250);
}

function convert() {
	if (!currentKey) {
		return;
	}
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const transform = transforms[currentKey];
	if (!transform) {
		return;
	}
	const raw = elements.input.value;
	if (!raw.trim()) {
		elements.output.value = "";
		setStatus("輸入為空，沒有輸出");
		return;
	}
	try {
		const result = transform.run(raw);
		if (!result) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (result.error) {
			elements.output.value = "";
			setStatus(`⚠️ ${result.error}`, true);
			return;
		}
		elements.output.value = result.result || "";
		setStatus("完成", false, "ready");
	} catch (err) {
		elements.output.value = "";
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function copyOutput() {
	const text = elements.output.value;
	if (!text) {
		setStatus("沒有可複製的內容", true);
		return;
	}
	navigator.clipboard.writeText(text).then(
		() => setStatus("已複製到剪貼簿"),
		() => setStatus("無法存取剪貼簿", true),
	);
}

function clearAll() {
	elements.input.value = "";
	elements.output.value = "";
	setStatus("已清除");
}

function handleHotkeys(e) {
	const mod = e.metaKey || e.ctrlKey;
	if (!mod) return;
	const key = e.key.toLowerCase();
	if (key === "l") {
		e.preventDefault();
		clearAll();
	} else if (key === "enter") {
		e.preventDefault();
		scheduleConvert(true);
	}
}

function setStatus(text, isError = false, tone = "") {
	elements.status.textContent = text;
	if (isError) {
		elements.status.dataset.state = "error";
		return;
	}
	if (tone) {
		elements.status.dataset.state = tone;
	} else {
		elements.status.dataset.state = "";
	}
}

async function loadWasm() {
	setStatus("載入 WebAssembly...");
	try {
		if (!wasmInitPromise) {
			wasmInitPromise = initWasm();
		}
		await wasmInitPromise;
		wasmReady = true;
		setStatus("WebAssembly 就緒，可以開始轉換！", false, "ready");
		if (elements.input.value.trim()) {
			scheduleConvert(true);
		}
	} catch (err) {
		console.error(err);
		setStatus(`無法載入 WASM: ${err.message}`, true);
	}
}

async function initWasm() {
	if (typeof WebAssembly === "undefined") {
		throw new Error("瀏覽器不支援 WebAssembly");
	}
	if (typeof Go === "undefined") {
		throw new Error("wasm_exec.js 尚未載入");
	}
	const go = new Go();
	let instance;
	if (WebAssembly.instantiateStreaming) {
		const result = await WebAssembly.instantiateStreaming(
			fetch("/app.wasm"),
			go.importObject,
		);
		instance = result.instance;
	} else {
		const response = await fetch("/app.wasm");
		const bytes = await response.arrayBuffer();
		const result = await WebAssembly.instantiate(bytes, go.importObject);
		instance = result.instance;
	}
	go.run(instance);
}

function invokeWasm(fn, text) {
	if (typeof fn !== "function") {
		return { error: "WASM 尚未載入完成" };
	}
	const res = fn(text);
	if (!res) {
		return { error: "WASM 尚未回傳結果" };
	}
	return res;
}

function runPipeline(fns, input) {
	let current = input;
	for (const fn of fns) {
		const res = invokeWasm(fn, current);
		if (!res || res.error) {
			return res;
		}
		current = res.result || "";
	}
	return { result: current };
}
