package convert

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_JSONYAMLConversions(t *testing.T) {
	yamlOut, err := JSONToYAML(sampleJSON)
	require.NoError(t, err)
	require.Contains(t, yamlOut, "name:")
	require.Contains(t, yamlOut, "age:")

	jsonBack, err := YAMLToJSON(yamlOut)
	require.NoError(t, err)
	require.Contains(t, jsonBack, `"name": "Alice"`)
	require.Contains(t, jsonBack, `"age": 30`)
}

func Benchmark_JSONYAMLConversions(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		yamlOut, _ := JSONToYAML(sampleJSON)
		_, _ = YAMLToJSON(yamlOut)
	}
}

func Fuzz_JSONYAMLRoundTrip(f *testing.F) {
	f.Add(sampleJSON)
	f.Add(sampleNestedJSON)
	f.Fuzz(func(t *testing.T, input string) {
		yamlOut, err := JSONToYAML(input)
		if err != nil {
			t.Skip()
		}
		jsonBack, err := YAMLToJSON(yamlOut)
		if err != nil {
			t.Skip()
		}
		require.NotEmpty(t, jsonBack)
	})
}

func Test_JSONTOMLConversions(t *testing.T) {
	tomlOut, err := JSONToTOML(sampleJSON)
	require.NoError(t, err)
	require.Contains(t, tomlOut, "name")
	jsonBack, err := TOMLToJSON(tomlOut)
	require.NoError(t, err)
	require.NotEmpty(t, jsonBack)
}

func Benchmark_JSONTOMLConversions(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		tomlOut, _ := JSONToTOML(sampleJSON)
		_, _ = TOMLToJSON(tomlOut)
	}
}

func Test_JSONSchemaRoundTrip(t *testing.T) {
	schema, err := JSONToSchema(sampleNestedJSON)
	require.NoError(t, err)
	require.Contains(t, schema, "object")
	sample, err := SchemaToJSON(schema)
	require.NoError(t, err)
	require.Contains(t, sample, "name")
}

func Benchmark_JSONSchemaRoundTrip(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		schema, _ := JSONToSchema(sampleNestedJSON)
		_, _ = SchemaToJSON(schema)
	}
}

func Test_SchemaToGoStruct(t *testing.T) {
	schema, err := JSONToSchema(sampleSchemaJSON)
	require.NoError(t, err)
	goStruct, err := SchemaToGoStruct(schema)
	require.NoError(t, err)
	require.Contains(t, goStruct, "type AutoGenerated struct")
}

func Test_YAMLAndTOMLToGoStruct(t *testing.T) {
	yamlGo, err := YAMLToGoStruct(sampleYAML)
	require.NoError(t, err)
	require.Contains(t, yamlGo, "type AutoGenerated struct")
	tomlGo, err := TOMLToGoStruct(sampleTOML)
	require.NoError(t, err)
	require.Contains(t, tomlGo, "type AutoGenerated struct")
}

func Test_GoStructBackToFormats(t *testing.T) {
	yamlOut, err := GoStructToYAML(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, yamlOut, "name:")
	tomlOut, err := GoStructToTOML(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, tomlOut, "name =")
	schemaOut, err := GoStructToSchema(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, schemaOut, "properties")
}
