package convert

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_JSONToGoStruct(t *testing.T) {
	out, err := JSONToGoStruct(sampleJSON)
	require.NoError(t, err)
	require.Contains(t, out, "type AutoGenerated")
	require.Contains(t, out, "Name string")
	require.Contains(t, out, "Age  int")
}

func Benchmark_JSONToGoStruct(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = JSONToGoStruct(sampleJSON)
	}
}

func Fuzz_JSONToGoStruct(f *testing.F) {
	f.Add(sampleJSON)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = JSONToGoStruct(input)
	})
}

func Test_GoStructToJSON(t *testing.T) {
	out, err := GoStructToJSON(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, out, `"name"`)
	require.Contains(t, out, `"age"`)
}

func Benchmark_GoStructToJSON(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = GoStructToJSON(sampleGoStruct)
	}
}

func Fuzz_GoStructToJSON(f *testing.F) {
	f.Add(sampleGoStruct)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = GoStructToJSON(input)
	})
}
