package convert

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_JSONToGraphQL(t *testing.T) {
	gql, err := JSONToGraphQL(sampleJSON)
	require.NoError(t, err)
	require.Contains(t, gql, "type AutoGenerated")
}

func Benchmark_JSONToGraphQL(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = JSONToGraphQL(sampleJSON)
	}
}

func Fuzz_JSONToGraphQL(f *testing.F) {
	f.Add(sampleJSON)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = JSONToGraphQL(input)
	})
}

func Test_GraphQLToJSON(t *testing.T) {
	src := "type A { id: Int name: String }"
	out, err := GraphQLToJSON(src)
	require.NoError(t, err)
	require.Contains(t, out, `"id"`)
}

func Benchmark_GraphQLToJSON(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	src := "type A { id: Int name: String }"
	for i := 0; i < b.N; i++ {
		_, _ = GraphQLToJSON(src)
	}
}

func Fuzz_GraphQLToJSON(f *testing.F) {
	f.Add("type A { x: Int }")
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = GraphQLToJSON(input)
	})
}

func Test_GoStructToGraphQL(t *testing.T) {
	out, err := GoStructToGraphQL(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, out, "type User")
}

func Test_GoStructToGraphQL_PreservesComments(t *testing.T) {
	const src = `
type GuessSetting struct {
	// channel identifier
	ChannelID string ` + "`json:\"channel_id\"`" + `
	// user reference
	UserRef string ` + "`json:\"user_ref\"`" + `
}`
	out, err := GoStructToGraphQL(src)
	require.NoError(t, err)
	require.Contains(t, out, "# channel identifier")
	require.Contains(t, out, "# user reference")
	require.Less(t,
		strings.Index(out, "channelID: String"),
		strings.Index(out, "userRef: String"))
}

func Benchmark_GoStructToGraphQL(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = GoStructToGraphQL(sampleGoStruct)
	}
}

func Fuzz_GoStructToGraphQL(f *testing.F) {
	f.Add(sampleGoStruct)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = GoStructToGraphQL(input)
	})
}

func Test_GraphQLToGoStruct(t *testing.T) {
	src := "type Person { id: Int name: String }"
	out, err := GraphQLToGoStruct(src)
	require.NoError(t, err)
	require.Contains(t, out, "type Person struct")
}

func Test_GraphQLToGoStruct_PreservesComments(t *testing.T) {
	src := `
type GuessSetting {
  # channel identifier
  channelID: String
  # user reference
  userRef: Int
}`
	out, err := GraphQLToGoStruct(src)
	require.NoError(t, err)
	require.Contains(t, out, "// channel identifier")
	require.Contains(t, out, "// user reference")
	idxChannel := strings.Index(out, "ChannelID string")
	idxUser := strings.Index(out, "UserRef int")
	require.NotEqual(t, -1, idxChannel)
	require.NotEqual(t, -1, idxUser)
	require.Less(t, idxChannel, idxUser)
}

func Benchmark_GraphQLToGoStruct(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	src := "type Person { id: Int name: String }"
	for i := 0; i < b.N; i++ {
		_, _ = GraphQLToGoStruct(src)
	}
}

func Fuzz_GraphQLToGoStruct(f *testing.F) {
	f.Add("type Item { n: Int }")
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = GraphQLToGoStruct(input)
	})
}
