package convert

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_JSONToProto(t *testing.T) {
	out, err := JSONToProto(sampleJSON)
	require.NoError(t, err)
	require.Contains(t, out, "message AutoGenerated")
}

func Benchmark_JSONToProto(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = JSONToProto(sampleJSON)
	}
}

func Fuzz_JSONToProto(f *testing.F) {
	f.Add(sampleJSON)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = JSONToProto(input)
	})
}

func Test_ProtoToJSON(t *testing.T) {
	src := "message A { int32 id = 1; string name = 2; }"
	out, err := ProtoToJSON(src)
	require.NoError(t, err)
	require.Contains(t, out, `"id"`)
}

func Benchmark_ProtoToJSON(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	src := "message A { int32 id = 1; string name = 2; }"
	for i := 0; i < b.N; i++ {
		_, _ = ProtoToJSON(src)
	}
}

func Fuzz_ProtoToJSON(f *testing.F) {
	f.Add("message A { int32 id = 1; }")
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = ProtoToJSON(input)
	})
}

func Test_GoStructToProto(t *testing.T) {
	out, err := GoStructToProto(sampleGoStruct)
	require.NoError(t, err)
	require.Contains(t, out, "message User")
}

func Test_GoStructToProto_PreservesComments(t *testing.T) {
	const src = `
type GuessSetting struct {
	// channel identifier
	ChannelID string ` + "`json:\"channel_id\"`" + `
	// tracked users
	UserIDs []int ` + "`json:\"user_ids\"`" + `
}`
	out, err := GoStructToProto(src)
	require.NoError(t, err)
	require.Contains(t, out, "// channel identifier")
	require.Contains(t, out, "// tracked users")
	require.Contains(t, out, "repeated int32 user_ids = 2;")
	require.Less(t,
		strings.Index(out, "channel_id = 1"),
		strings.Index(out, "user_ids = 2"))
}

func Benchmark_GoStructToProto(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = GoStructToProto(sampleGoStruct)
	}
}

func Fuzz_GoStructToProto(f *testing.F) {
	f.Add(sampleGoStruct)
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = GoStructToProto(input)
	})
}

func Test_ProtoToGoStruct(t *testing.T) {
	src := "message Person { int32 id = 1; string name = 2; }"
	out, err := ProtoToGoStruct(src)
	require.NoError(t, err)
	require.Contains(t, out, "type Person struct")
}

func Test_ProtoToGoStruct_PreservesComments(t *testing.T) {
	src := `
message GuessSetting {
  // channel identifier
  string channel_id = 1;
  // user bucket
  repeated int32 user_ids = 2;
}`
	out, err := ProtoToGoStruct(src)
	require.NoError(t, err)
	require.Contains(t, out, "// channel identifier")
	require.Contains(t, out, "// user bucket")
	require.Contains(t, out, "[]int32")
	idxChannel := strings.Index(out, "ChannelId string")
	idxUsers := strings.Index(out, "UserIds []int32")
	require.NotEqual(t, -1, idxChannel)
	require.NotEqual(t, -1, idxUsers)
	require.Less(t, idxChannel, idxUsers)
}

func Benchmark_ProtoToGoStruct(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()
	src := "message Person { int32 id = 1; string name = 2; }"
	for i := 0; i < b.N; i++ {
		_, _ = ProtoToGoStruct(src)
	}
}

func Fuzz_ProtoToGoStruct(f *testing.F) {
	f.Add("message X { int32 n = 1; }")
	f.Fuzz(func(t *testing.T, input string) {
		_, _ = ProtoToGoStruct(input)
	})
}
