const formats = [
	"JSON",
	"Go Struct",
	"YAML",
	"TOML",
	"JSON Schema",
	"GraphQL Schema",
	"Protobuf",
];

const supportedFormats = new Set(formats);

const samples = {
	JSON: '{\n  "name": "Ricky",\n  "age": 27\n}',
	"Go Struct":
		'type AutoGenerated struct {\n  UserId string `json:"user_id"`\n}\n',
	YAML: "name: Ricky\nage: 27",
	TOML: 'name = "Ricky"\nage = 27',
	"JSON Schema": `{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "number" }
  },
  "required": ["name"]
}`,
	"GraphQL Schema": `type AutoGenerated {
  userID: String!
}`,
	Protobuf: `message AutoGenerated {
  string user_id = 1;
}`,
};

const elements = {};
let currentKey = "JSON|Go Struct";
let wasmReady = false;
let debounceTimer = null;
let wasmInitPromise = null;

document.addEventListener("DOMContentLoaded", () => {
	cacheElements();
	bindEvents();
	ensureMode();
	loadWasm();
});

function cacheElements() {
	elements.from = document.getElementById("fromSelect");
	elements.to = document.getElementById("toSelect");
	elements.swap = document.getElementById("swap");
	elements.input = document.getElementById("input");
	elements.output = document.getElementById("output");
	elements.copy = document.getElementById("copy");
	elements.clear = document.getElementById("clear");
	elements.status = document.getElementById("status");
	elements.inputLabel = document.getElementById("inputLabel");
	elements.outputLabel = document.getElementById("outputLabel");
}

function bindEvents() {
	elements.from.addEventListener("change", () => onModeChange("from"));
	elements.to.addEventListener("change", () => onModeChange("to"));
	elements.swap.addEventListener("click", onSwap);
	elements.copy.addEventListener("click", copyOutput);
	elements.clear.addEventListener("click", clearAll);
	elements.input.addEventListener("input", () => scheduleConvert());
	window.addEventListener("keydown", handleHotkeys);
}

function onModeChange(source) {
	ensureDistinctSelections(source);
	if (!ensureMode()) {
		setStatus("這個組合尚未支援", true);
	}
}

function onSwap() {
	const from = elements.from.value;
	const to = elements.to.value;
	elements.from.value = to;
	elements.to.value = from;
	const oldInput = elements.input.value;
	elements.input.value = elements.output.value;
	elements.output.value = oldInput;
	onModeChange("swap");
}

function ensureMode() {
	const from = elements.from.value;
	const to = elements.to.value;
	if (!supportedFormats.has(from) || !supportedFormats.has(to) || from === to) {
		currentKey = null;
		return false;
	}
	currentKey = `${from}|${to}`;
	elements.inputLabel.textContent = from;
	elements.outputLabel.textContent = to;
	elements.input.placeholder = samples[from] || "";
	scheduleConvert(true);
	return true;
}

function ensureDistinctSelections(source) {
	if (elements.from.value !== elements.to.value) {
		return;
	}
	const adjustTarget = source === "from" ? elements.to : elements.from;
	const conflict = source === "from" ? elements.from.value : elements.to.value;
	const fallback = Array.from(adjustTarget.options).find(
		(opt) => opt.value !== conflict,
	);
	if (fallback) {
		adjustTarget.value = fallback.value;
	}
}

function scheduleConvert(immediate = false) {
	if (immediate) {
		convert();
		return;
	}
	clearTimeout(debounceTimer);
	debounceTimer = setTimeout(() => convert(), 250);
}

function convert() {
	const from = elements.from.value;
	const to = elements.to.value;
	if (!supportedFormats.has(from) || !supportedFormats.has(to)) {
		setStatus("不支援的格式", true);
		return;
	}
	if (from === to) {
		setStatus("輸入與輸出格式相同", true);
		return;
	}
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const raw = elements.input.value;
	if (!raw.trim()) {
		elements.output.value = "";
		setStatus("輸入為空，沒有輸出");
		return;
	}
	try {
		const result = window.transformFormat(from, to, raw);
		if (!result) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (result.error) {
			elements.output.value = "";
			setStatus(`⚠️ ${result.error}`, true);
			return;
		}
		elements.output.value = result.result || "";
		setStatus("完成", false, "ready");
	} catch (err) {
		elements.output.value = "";
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function copyOutput() {
	const text = elements.output.value;
	if (!text) {
		setStatus("沒有可複製的內容", true);
		return;
	}
	navigator.clipboard.writeText(text).then(
		() => setStatus("已複製到剪貼簿"),
		() => setStatus("無法存取剪貼簿", true),
	);
}

function clearAll() {
	elements.input.value = "";
	elements.output.value = "";
	setStatus("已清除");
}

function handleHotkeys(e) {
	const mod = e.metaKey || e.ctrlKey;
	if (!mod) return;
	const key = e.key.toLowerCase();
	if (key === "l") {
		e.preventDefault();
		clearAll();
	} else if (key === "enter") {
		e.preventDefault();
		scheduleConvert(true);
	}
}

function setStatus(text, isError = false, tone = "") {
	elements.status.textContent = text;
	if (isError) {
		elements.status.dataset.state = "error";
		return;
	}
	if (tone) {
		elements.status.dataset.state = tone;
	} else {
		elements.status.dataset.state = "";
	}
}

async function loadWasm() {
	setStatus("載入 WebAssembly...");
	try {
		if (!wasmInitPromise) {
			wasmInitPromise = initWasm();
		}
		await wasmInitPromise;
		wasmReady = true;
		setStatus("WebAssembly 就緒，可以開始轉換！", false, "ready");
		if (elements.input.value.trim()) {
			scheduleConvert(true);
		}
	} catch (err) {
		console.error(err);
		setStatus(`無法載入 WASM: ${err.message}`, true);
	}
}

async function initWasm() {
	if (typeof WebAssembly === "undefined") {
		throw new Error("瀏覽器不支援 WebAssembly");
	}
	if (typeof Go === "undefined") {
		throw new Error("wasm_exec.js 尚未載入");
	}
	const go = new Go();
	let instance;
	if (WebAssembly.instantiateStreaming) {
		const result = await WebAssembly.instantiateStreaming(
			fetch("app.wasm"),
			go.importObject,
		);
		instance = result.instance;
	} else {
		const response = await fetch("app.wasm");
		const bytes = await response.arrayBuffer();
		const result = await WebAssembly.instantiate(bytes, go.importObject);
		instance = result.instance;
	}
	go.run(instance);
}
