const formats = [
	"JSON",
	"Go Struct",
	"YAML",
	"TOML",
	"XML",
	"JSON Schema",
	"GraphQL Schema",
	"Protobuf",
];

const samples = {
	JSON: '{\n  "name": "Ricky",\n  "age": 27\n}',
	XML: `<root>\n  <name>Ricky</name>\n  <age>27</age>\n</root>`,
	"Go Struct":
		'type AutoGenerated struct {\n  UserID string `json:"user_id"`\n}\n',
	YAML: "name: Ricky\nage: 27",
	TOML: 'name = "Ricky"\nage = 27',
	"JSON Schema": `{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "number" }
  },
  "required": ["name"]
}`,
	"GraphQL Schema": `type AutoGenerated {
  userID: String!
}`,
	Protobuf: `message AutoGenerated {
  string user_id = 1;
}`,
};

const coderTools = [
	{
		id: "coder-encode",
		mode: "encode",
		label: "Base Encoders",
		description: "Base32/64/85/91 encodings.",
	},
	{
		id: "coder-decode",
		mode: "decode",
		label: "Base Decoders",
		description: "Decode BaseX back to plain text.",
	},
	{
		id: "coder-hash",
		mode: "hash",
		label: "Hash",
		description: "Hashes from Go's stdlib.",
	},
	{
		id: "coder-url",
		pair: "url",
		label: "URL Encode/Decode",
		description: "Bidirectional URL percent-encoding helper.",
	},
	{
		id: "coder-jwt",
		pair: "jwt",
		label: "JWT Encode/Decode",
		description: "Sign JSON payloads and inspect JWT tokens.",
	},
];

const toolGroups = [
	{
		name: "Converters",
		tools: [
			{
				id: "format",
				label: "Format Converter",
				description: "Convert between structured data formats.",
			},
			{
				id: "converter-html-md",
				label: "HTML ↔ Markdown",
				description: "Markdown 及 HTML 互相轉換。",
			},
			{
				id: "converter-number-bases",
				label: "Number Bases",
				description: "Binary / Octal / Decimal / Hex 同步轉換。",
			},
			{
				id: "converter-ipv4",
				label: "IPv4 工具",
				description: "CIDR、Range、等值表示。",
			},
		],
	},
	{
		name: "Coder",
		tools: coderTools.map((tool) => ({
			id: tool.id,
			label: `${tool.label}`,
			description: tool.description,
		})),
	},
	{
		name: "Generator",
		tools: [
			{
				id: "generator-uuid",
				label: "UUID Generator",
				description: "產生 UUID v1~v5。",
			},
		],
	},
];

const coderToolModes = {};
const coderMainTools = new Set();
const pairToolSet = new Set();
coderTools.forEach((tool) => {
	if (tool.mode) {
		coderToolModes[tool.id] = tool.mode;
		coderMainTools.add(tool.id);
	}
	if (tool.pair) {
		pairToolSet.add(tool.id);
	}
});
const converterPairTools = ["converter-html-md"];
converterPairTools.forEach((id) => pairToolSet.add(id));
const coderToolSet = new Set([...coderMainTools, ...pairToolSet]);
const numberToolSet = new Set(["converter-number-bases"]);
const ipv4ToolSet = new Set(["converter-ipv4"]);
const generatorToolSet = new Set(["generator-uuid"]);
const coderModes = ["encode", "decode", "hash"];
const coderModeTitles = {
	encode: "Encode",
	decode: "Decode",
	hash: "Hash",
};
let coderMode = "encode";

function isCoderToolId(toolId) {
	return coderToolSet.has(toolId);
}

function isCoderMainTool(toolId) {
	return coderMainTools.has(toolId);
}

function isPairToolId(toolId) {
	return pairToolSet.has(toolId);
}

function isNumberTool(toolId) {
	return numberToolSet.has(toolId);
}

function isIPv4Tool(toolId) {
	return ipv4ToolSet.has(toolId);
}

function isGeneratorTool(toolId) {
	return generatorToolSet.has(toolId);
}

const encodingGroups = [
	{
		id: "base32",
		label: "Base32",
		variants: [
			{ key: "base32_standard", label: "Standard" },
			{ key: "base32_standard_no_padding", label: "Standard · No padding" },
			{ key: "base32_hex", label: "Hex" },
			{ key: "base32_hex_no_padding", label: "Hex · No padding" },
		],
	},
	{
		id: "base64",
		label: "Base64",
		variants: [
			{ key: "base64_standard", label: "Standard" },
			{ key: "base64_raw_standard", label: "Standard · Raw" },
			{ key: "base64_url", label: "URL-safe" },
			{ key: "base64_raw_url", label: "URL-safe · Raw" },
		],
	},
	{
		id: "base85",
		label: "Base85",
		variants: [{ key: "base85_ascii85", label: "ASCII85" }],
	},
	{
		id: "base91",
		label: "Base91",
		variants: [{ key: "base91", label: "Standard" }],
	},
	{
		id: "base16",
		label: "Base16",
		variants: [{ key: "hex_upper", label: "Hex (uppercase)" }],
	},
];

const encodingVariantMap = new Map();
const allEncodingVariants = [];
encodingGroups.forEach((group) => {
	group.variants.forEach((variant) => {
		encodingVariantMap.set(variant.key, {
			group: group.label,
			label: variant.label,
		});
		allEncodingVariants.push({
			...variant,
			group: group.label,
		});
	});
});

let selectedDecoder =
	allEncodingVariants.length > 0 ? allEncodingVariants[0].key : "";

const hashGroups = [
	{
		label: "Message Digest",
		keys: ["md5", "sha1"],
	},
	{
		label: "SHA-2",
		keys: ["sha224", "sha256", "sha384", "sha512", "sha512_224", "sha512_256"],
	},
	{
		label: "Checksums",
		keys: ["crc32_ieee", "crc32_castagnoli", "crc64_iso", "crc64_ecma", "adler32"],
	},
	{
		label: "FNV",
		keys: ["fnv32", "fnv32a", "fnv64", "fnv64a", "fnv128", "fnv128a"],
	},
];

const hashLabels = {
	md5: "MD5",
	sha1: "SHA-1",
	sha224: "SHA-224",
	sha256: "SHA-256",
	sha384: "SHA-384",
	sha512: "SHA-512",
	sha512_224: "SHA-512/224",
	sha512_256: "SHA-512/256",
	crc32_ieee: "CRC32 (IEEE)",
	crc32_castagnoli: "CRC32 (Castagnoli)",
	crc64_iso: "CRC64 (ISO)",
	crc64_ecma: "CRC64 (ECMA)",
	adler32: "Adler32",
	fnv32: "FNV-1 32",
	fnv32a: "FNV-1a 32",
	fnv64: "FNV-1 64",
	fnv64a: "FNV-1a 64",
	fnv128: "FNV-1 128",
	fnv128a: "FNV-1a 128",
};

const coderModeDescriptions = {
	encode: "Encode text into multiple bases.",
	decode: "Decode text with your selected base.",
	hash: "Generate hashes provided by Go's standard library.",
};

const coderResultHints = {
	encode: "Base32 / Base64 / Base85 / Base91 / Hex",
	decode: "Decoded output",
	hash: "MD5 / SHA / CRC / FNV",
};

const coderPlaceholders = {
	encode: "輸入任意文字...",
	decode: "貼上要解碼的 Base32/64/85/91 內容...",
	hash: "輸入任意文字以產生 hash",
};

const pairToolConfigs = {
	"coder-url": {
		type: "url",
		inputLabel: "URL Encode",
		inputHint: "輸入原始文字，將自動轉成 URL encoded。",
		inputPlaceholder: "https://example.com/search?q=台北 101",
		outputLabel: "URL Decode",
		outputHint: "貼上已編碼的內容，自動解碼。",
		outputPlaceholder: "https%3A%2F%2Fexample.com%2Fsearch%3Fq%3D%E5%8F%B0%E5%8C%97101",
	},
	"coder-jwt": {
		type: "jwt",
		inputLabel: "JWT Payload (JSON)",
		inputHint: "輸入 payload JSON，選擇演算法後會自動生成 token。",
		inputPlaceholder: '{\n  "sub": "1234567890",\n  "name": "John Doe"\n}',
		outputLabel: "JWT Token",
		outputHint: "貼上 JWT token 以解碼 Payload。",
		outputPlaceholder: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....",
	},
	"converter-html-md": {
		type: "markdown",
		inputLabel: "Markdown → HTML",
		inputHint: "輸入 Markdown 內容，右側為 HTML。",
		inputPlaceholder: "# Title\n\n- item 1\n- item 2",
		outputLabel: "HTML → Markdown",
		outputHint: "貼上 HTML 內容可轉回 Markdown。",
		outputPlaceholder: "<h1>Title</h1>",
	},
};

const toolInfo = {};
toolGroups.forEach((group) => {
	group.tools.forEach((tool) => {
		toolInfo[tool.id] = tool;
	});
});

const supportedFormats = new Set(formats);

const elements = {};
let currentTool = "format";
let currentKey = "JSON|Go Struct";
let wasmReady = false;
let debounceTimer = null;
let coderTimer = null;
let wasmInitPromise = null;
let currentPairTool = null;
let pairSyncing = false;
let pairLastSource = "input";
let numberSyncing = false;
let uuidUppercase = false;
let currentUUIDs = {};
const uuidDisplayOrder = [
	"v1",
	"v2",
	"v3",
	"v4",
	"v5",
	"v6",
	"v7",
	"v8",
	"guid",
	"ulid",
];
const uuidDisplayLabels = {
	guid: "GUID",
	ulid: "ULID",
};

document.addEventListener("DOMContentLoaded", () => {
	cacheElements();
	initCoderControls();
	renderToolSidebar();
	initSidebarResizer();
	bindEvents();
	selectTool(currentTool);
	ensureMode();
	loadWasm();
});

function cacheElements() {
	elements.sidebar = document.getElementById("sidebar");
	elements.toolGroups = document.getElementById("toolGroups");
	elements.resizer = document.getElementById("sidebarResizer");
	elements.toolName = document.getElementById("toolName");
	elements.toolDesc = document.getElementById("toolDesc");
	elements.from = document.getElementById("fromSelect");
	elements.to = document.getElementById("toSelect");
	elements.swap = document.getElementById("swap");
	elements.copy = document.getElementById("copy");
	elements.clear = document.getElementById("clear");
	elements.input = document.getElementById("input");
	elements.output = document.getElementById("output");
	elements.status = document.getElementById("status");
	elements.inputLabel = document.getElementById("inputLabel");
	elements.outputLabel = document.getElementById("outputLabel");
	elements.formatInput = document.getElementById("formatInput");
	elements.minifyInput = document.getElementById("minifyInput");
	elements.formatOutput = document.getElementById("formatOutput");
	elements.minifyOutput = document.getElementById("minifyOutput");
	elements.converterWorkspace = document.getElementById("converterWorkspace");
	elements.coderWorkspace = document.getElementById("coderWorkspace");
	elements.coderInput = document.getElementById("coderInput");
	elements.coderResults = document.getElementById("coderResults");
	elements.coderWorkspaceTitle = document.getElementById(
		"coderWorkspaceTitle",
	);
	elements.decodeVariantWrap = document.getElementById("decodeVariantWrap");
	elements.decodeVariant = document.getElementById("decodeVariant");
	elements.coderResultHeading = document.getElementById("coderResultHeading");
	elements.coderResultHint = document.getElementById("coderResultHint");
	elements.coderModeHint = document.getElementById("coderModeHint");
	elements.pairWorkspace = document.getElementById("pairWorkspace");
	elements.pairInput = document.getElementById("pairInput");
	elements.pairOutput = document.getElementById("pairOutput");
	elements.pairInputLabel = document.getElementById("pairInputLabel");
	elements.pairOutputLabel = document.getElementById("pairOutputLabel");
	elements.pairInputHint = document.getElementById("pairInputHint");
	elements.pairOutputHint = document.getElementById("pairOutputHint");
	elements.jwtControls = document.getElementById("jwtControls");
	elements.jwtAlgorithm = document.getElementById("jwtAlgorithm");
	elements.jwtSecret = document.getElementById("jwtSecret");
	elements.pairOutputMeta = document.getElementById("pairOutputMeta");
	elements.numberWorkspace = document.getElementById("numberWorkspace");
	elements.numberBinary = document.getElementById("numberBinary");
	elements.numberOctal = document.getElementById("numberOctal");
	elements.numberDecimal = document.getElementById("numberDecimal");
	elements.numberHex = document.getElementById("numberHex");
	elements.ipv4Workspace = document.getElementById("ipv4Workspace");
	elements.ipv4Input = document.getElementById("ipv4Input");
	elements.ipv4Results = document.getElementById("ipv4Results");
	elements.generatorWorkspace = document.getElementById("generatorWorkspace");
	elements.uuidList = document.getElementById("uuidList");
	elements.uuidToggleCase = document.getElementById("uuidToggleCase");
	elements.uuidRegenerate = document.getElementById("uuidRegenerate");
}

function initCoderControls() {
	if (!elements.decodeVariant) return;
	const options = allEncodingVariants
		.map(
			(opt) =>
				`<option value="${opt.key}">${opt.group} · ${opt.label}</option>`,
		)
		.join("");
	elements.decodeVariant.innerHTML = options;
	if (
		selectedDecoder &&
		allEncodingVariants.some((variant) => variant.key === selectedDecoder)
	) {
		elements.decodeVariant.value = selectedDecoder;
	} else if (allEncodingVariants.length > 0) {
		selectedDecoder = allEncodingVariants[0].key;
		elements.decodeVariant.value = selectedDecoder;
	}
	updateCoderTexts();
	if (elements.coderResults) {
		renderCoderEmpty();
	}
}

function renderToolSidebar() {
	const nav = elements.toolGroups;
	toolGroups.forEach((group) => {
		const details = document.createElement("details");
		details.open = true;
		const summary = document.createElement("summary");
		summary.textContent = group.name;
		details.appendChild(summary);
		const wrapper = document.createElement("div");
		wrapper.className = "tool-buttons";
		group.tools.forEach((tool) => {
			const btn = document.createElement("button");
			btn.type = "button";
			btn.dataset.toolId = tool.id;
			btn.textContent = tool.label;
			btn.addEventListener("click", () => selectTool(tool.id));
			wrapper.appendChild(btn);
		});
		details.appendChild(wrapper);
		nav.appendChild(details);
	});
	updateToolButtons();
}

function initSidebarResizer() {
	let startX = 0;
	let startWidth = 0;
	const minWidth = 200;
	const maxWidth = 420;
	elements.resizer.addEventListener("mousedown", (event) => {
		startX = event.clientX;
		startWidth = elements.sidebar.offsetWidth;
		document.body.classList.add("resizing");
		const onMove = (e) => {
			const delta = e.clientX - startX;
			const newWidth = Math.min(
				maxWidth,
				Math.max(minWidth, startWidth + delta),
			);
			document.documentElement.style.setProperty(
				"--sidebar-width",
				`${newWidth}px`,
			);
		};
		const onUp = () => {
			document.body.classList.remove("resizing");
			document.removeEventListener("mousemove", onMove);
			document.removeEventListener("mouseup", onUp);
		};
		document.addEventListener("mousemove", onMove);
		document.addEventListener("mouseup", onUp);
	});
}

function bindEvents() {
	elements.from.addEventListener("change", ensureMode);
	elements.to.addEventListener("change", ensureMode);
	elements.swap.addEventListener("click", onSwap);
	elements.copy.addEventListener("click", copyOutput);
	elements.clear.addEventListener("click", clearAll);
	elements.input.addEventListener("input", () => scheduleConvert());
	elements.formatInput.addEventListener("click", () =>
		formatField(elements.input, elements.from.value, false),
	);
	elements.minifyInput.addEventListener("click", () =>
		formatField(elements.input, elements.from.value, true),
	);
	elements.formatOutput.addEventListener("click", () =>
		formatField(elements.output, elements.to.value, false),
	);
	elements.minifyOutput.addEventListener("click", () =>
		formatField(elements.output, elements.to.value, true),
	);
	elements.coderInput.addEventListener("input", () => scheduleCoder());
	if (elements.decodeVariant) {
		elements.decodeVariant.addEventListener("change", (event) => {
			selectedDecoder = event.target.value;
			updateCoderTexts();
			scheduleCoder(true);
		});
	}
	elements.coderResults.addEventListener("click", (event) => {
		const btn = event.target.closest("button[data-value]");
		if (!btn) return;
		const value = btn.dataset.value || "";
		if (!value) return;
		const label = btn.dataset.label || "結果";
		navigator.clipboard.writeText(value).then(
			() => setStatus(`已複製 ${label}`, false, "ready"),
			() => setStatus("無法存取剪貼簿", true),
		);
	});
	if (elements.pairInput) {
		elements.pairInput.addEventListener("input", () =>
			handlePairInput("input"),
		);
	}
	if (elements.pairOutput) {
		elements.pairOutput.addEventListener("input", () =>
			handlePairInput("output"),
		);
	}
	if (elements.jwtAlgorithm) {
		elements.jwtAlgorithm.addEventListener("change", () => {
			if (currentPairTool === "coder-jwt") {
				runPairConversion("input");
			}
		});
	}
	if (elements.jwtSecret) {
		elements.jwtSecret.addEventListener("input", () => {
			if (
				currentPairTool === "coder-jwt" &&
				pairLastSource === "input" &&
				elements.pairInput.value.trim()
			) {
				runPairConversion("input");
			}
		});
	}
	if (elements.numberBinary) {
		elements.numberBinary.addEventListener("input", () =>
			handleNumberInput("binary"),
		);
	}
	if (elements.numberOctal) {
		elements.numberOctal.addEventListener("input", () =>
			handleNumberInput("octal"),
		);
	}
	if (elements.numberDecimal) {
		elements.numberDecimal.addEventListener("input", () =>
			handleNumberInput("decimal"),
		);
	}
	if (elements.numberHex) {
		elements.numberHex.addEventListener("input", () =>
			handleNumberInput("hex"),
		);
	}
	if (elements.ipv4Input) {
		elements.ipv4Input.addEventListener("input", () => runIPv4Conversion());
	}
	if (elements.uuidRegenerate) {
		elements.uuidRegenerate.addEventListener("click", () =>
			refreshUUIDs(true),
		);
	}
	if (elements.uuidToggleCase) {
		elements.uuidToggleCase.addEventListener("click", () => {
			uuidUppercase = !uuidUppercase;
			refreshUUIDDisplay();
			elements.uuidToggleCase.dataset.upper = uuidUppercase ? "true" : "false";
		});
	}
	window.addEventListener("keydown", handleHotkeys);
}

function updateCoderTexts() {
	if (elements.coderWorkspaceTitle) {
		const modeTitle = coderModeTitles[coderMode] || coderMode;
		elements.coderWorkspaceTitle.textContent = `${modeTitle}`;
	}
	if (elements.coderModeHint) {
		elements.coderModeHint.textContent =
			coderModeDescriptions[coderMode] || "";
	}
	if (elements.coderResultHeading) {
		const heading =
			coderMode === "hash"
				? "Hash Digests"
				: coderMode === "decode"
					? "Decode"
					: "Encodings";
		elements.coderResultHeading.textContent = heading;
	}
	if (elements.coderResultHint) {
		if (coderMode === "decode") {
			const info = encodingVariantMap.get(selectedDecoder);
			elements.coderResultHint.textContent =
				info && info.group
					? `${info.group} · ${info.label}`
					: coderResultHints.decode;
		} else {
			elements.coderResultHint.textContent =
				coderResultHints[coderMode] || "";
		}
	}
	if (elements.decodeVariantWrap) {
		elements.decodeVariantWrap.classList.toggle(
			"hidden",
			coderMode !== "decode",
		);
	}
	if (elements.coderInput) {
		elements.coderInput.placeholder =
			coderPlaceholders[coderMode] || coderPlaceholders.encode;
	}
}

function renderCoderEmpty() {
	const message =
		coderMode === "decode"
			? "貼上要解碼的內容以查看結果"
			: "輸入內容以查看結果";
	elements.coderResults.innerHTML = `<div class="muted">${message}</div>`;
}

function renderEncodeResults(map) {
	if (!map || Object.keys(map).length === 0) {
		renderCoderEmpty();
		return;
	}
	const blocks = encodingGroups
		.map((group) => {
			const entries = group.variants
				.map((variant) => ({
					label: variant.label,
					value: map[variant.key],
					copyLabel: `${group.label} · ${variant.label}`,
				}))
				.filter((entry) => typeof entry.value === "string");
			if (!entries.length) return "";
			return renderGroupBlock(group.label, entries);
		})
		.filter(Boolean);
	if (blocks.length === 0) {
		renderCoderEmpty();
		return;
	}
	elements.coderResults.innerHTML = `
    <div class="coder-groups">
      <div class="coder-output-grid">${blocks.join("")}</div>
    </div>
  `;
}

function renderDecodeResult(value, label) {
	const block = renderGroupBlock(label || "Decoded", [
		{
			label: label || "Decoded",
			value: value || "",
			copyLabel: label || "Decoded",
		},
	]);
	elements.coderResults.innerHTML = `
    <div class="coder-groups">
      <div class="coder-output-grid">${block}</div>
    </div>
  `;
}

function renderHashResults(map) {
	if (!map || Object.keys(map).length === 0) {
		renderCoderEmpty();
		return;
	}
	const blocks = hashGroups
		.map((group) => {
			const entries = group.keys
				.map((key) => {
					const value = map[key];
					if (typeof value !== "string") {
						return null;
					}
					const label = hashLabels[key] || key;
					return {
						label,
						value,
						copyLabel: label,
					};
				})
				.filter(Boolean);
			if (!entries.length) return "";
			return renderGroupBlock(group.label, entries);
		})
		.filter(Boolean);
	if (blocks.length === 0) {
		renderCoderEmpty();
		return;
	}
	elements.coderResults.innerHTML = `
    <div class="coder-groups">
      <div class="coder-output-grid">${blocks.join("")}</div>
    </div>
  `;
}

function renderGroupBlock(title, entries) {
	const rows = entries.map(renderEntryRow).join("");
	if (!rows.trim()) return "";
	const safeTitle = escapeHTML(title || "Result");
	return `
    <section class="coder-output-block">
      <header>${safeTitle}</header>
      <div class="coder-output-entries">
        ${rows}
      </div>
    </section>
  `;
}

function renderEntryRow(entry) {
	const safeLabel = escapeHTML(entry.label || "Result");
	const safeValue = escapeHTML(entry.value || "");
	const attrValue = escapeAttr(entry.value || "");
	const buttonLabel = escapeAttr(entry.copyLabel || entry.label || "Result");
	return `
    <div class="coder-entry">
      <div class="coder-entry-meta">
        <span>${safeLabel}</span>
        <button type="button" data-label="${buttonLabel}" data-value="${attrValue}">Copy</button>
      </div>
      <textarea readonly spellcheck="false">${safeValue}</textarea>
    </div>
  `;
}

function activatePairTool(toolId) {
	currentPairTool = toolId;
	pairLastSource = "input";
	const config = pairToolConfigs[toolId];
	if (!config || !elements.pairWorkspace) return;
	if (elements.pairInputLabel) {
		elements.pairInputLabel.textContent = config.inputLabel || "Encode";
	}
	if (elements.pairOutputLabel) {
		elements.pairOutputLabel.textContent = config.outputLabel || "Decode";
	}
	if (elements.pairInputHint) {
		elements.pairInputHint.textContent = config.inputHint || "";
	}
	if (elements.pairOutputHint) {
		elements.pairOutputHint.textContent = config.outputHint || "";
	}
	if (elements.pairInput) {
		elements.pairInput.placeholder = config.inputPlaceholder || "";
		elements.pairInput.value = "";
	}
	if (elements.pairOutput) {
		elements.pairOutput.placeholder = config.outputPlaceholder || "";
		elements.pairOutput.value = "";
	}
	const showJWT = config.type === "jwt";
	if (elements.jwtControls) {
		elements.jwtControls.classList.toggle("hidden", !showJWT);
	}
	if (!showJWT) {
		updatePairMeta(null);
		if (elements.jwtSecret) {
			elements.jwtSecret.value = "";
		}
	} else if (elements.jwtAlgorithm && !elements.jwtAlgorithm.value) {
		elements.jwtAlgorithm.value = "HS256";
	}
	updatePairMeta(null);
	setStatus("就緒", false, "ready");
}

function handlePairInput(source) {
	if (!isPairToolId(currentTool) || pairSyncing) return;
	runPairConversion(source);
}

function runPairConversion(source) {
	if (!isPairToolId(currentTool)) return;
	const config = pairToolConfigs[currentTool];
	if (!config) return;
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	pairLastSource = source;
	const inputValue = elements.pairInput ? elements.pairInput.value : "";
	const outputValue = elements.pairOutput ? elements.pairOutput.value : "";
	if (config.type === "url") {
		if (source === "input") {
			if (!inputValue) {
				setPairField(elements.pairOutput, "");
				setStatus("已清除");
				return;
			}
			const response = window.urlEncode(inputValue);
			if (!response || response.error) {
				setStatus(response?.error || "URL encode 失敗", true);
				return;
			}
			setPairField(elements.pairOutput, response.result || "");
			setStatus("完成", false, "ready");
			return;
		}
		if (!outputValue) {
			setPairField(elements.pairInput, "");
			setStatus("已清除");
			return;
		}
		const response = window.urlDecode(outputValue);
		if (!response || response.error) {
			setStatus(response?.error || "URL decode 失敗", true);
			return;
		}
		setPairField(elements.pairInput, response.result || "");
		setStatus("完成", false, "ready");
		return;
	}
	if (config.type === "markdown") {
		if (source === "input") {
			if (!inputValue.trim()) {
				setPairField(elements.pairOutput, "");
				setStatus("已清除");
				return;
			}
			let response;
			try {
				response = window.markdownToHTML(inputValue);
			} catch (err) {
				setStatus(err.message, true);
				return;
			}
			if (!response || response.error) {
				setStatus(response?.error || "Markdown 轉換失敗", true);
				return;
			}
			setPairField(elements.pairOutput, response.result || "");
			setStatus("完成", false, "ready");
			return;
		}
		if (!outputValue.trim()) {
			setPairField(elements.pairInput, "");
			setStatus("已清除");
			return;
		}
		let response;
		try {
			response = window.htmlToMarkdown(outputValue);
		} catch (err) {
			setStatus(err.message, true);
			return;
		}
		if (!response || response.error) {
			setStatus(response?.error || "HTML 轉換失敗", true);
			return;
		}
		setPairField(elements.pairInput, response.result || "");
		setStatus("完成", false, "ready");
		return;
	}
	if (config.type === "jwt") {
		if (source === "input") {
			if (!inputValue.trim()) {
				setPairField(elements.pairOutput, "");
				updatePairMeta(null);
				setStatus("已清除");
				return;
			}
			const secret = elements.jwtSecret ? elements.jwtSecret.value : "";
			if (!secret.trim()) {
				setStatus("請輸入 secret", true);
				return;
			}
			const algorithm = elements.jwtAlgorithm
				? elements.jwtAlgorithm.value
				: "HS256";
			let response;
			try {
				response = window.jwtEncode(inputValue, secret, algorithm);
			} catch (err) {
				setStatus(err.message, true);
				return;
			}
			if (!response || response.error) {
				setStatus(response?.error || "JWT encode 失敗", true);
				return;
			}
			const token =
				(response.result && response.result.token) || response.result || "";
			setPairField(elements.pairOutput, token);
			updatePairMeta(null);
			setStatus("完成", false, "ready");
			return;
		}
		if (!outputValue.trim()) {
			setPairField(elements.pairInput, "");
			updatePairMeta(null);
			setStatus("已清除");
			return;
		}
		let response;
		try {
			response = window.jwtDecode(outputValue);
		} catch (err) {
			setStatus(err.message, true);
			return;
		}
		if (!response || response.error) {
			setStatus(response?.error || "JWT decode 失敗", true);
			return;
		}
		const info = response.result || {};
		if (info.payload) {
			setPairField(elements.pairInput, info.payload);
		}
		if (info.algorithm && elements.jwtAlgorithm) {
			elements.jwtAlgorithm.value = info.algorithm;
		}
		updatePairMeta(info);
		setStatus("完成", false, "ready");
		return;
	}
}

function setPairField(target, value) {
	if (!target) return;
	pairSyncing = true;
	target.value = value || "";
	pairSyncing = false;
}

function updatePairMeta(info) {
	if (!elements.pairOutputMeta) return;
	if (!info || currentPairTool !== "coder-jwt") {
		elements.pairOutputMeta.classList.add("hidden");
		elements.pairOutputMeta.textContent = "";
		return;
	}
	const sections = [];
	if (info.header) {
		sections.push(`Header:\n${info.header}`);
	}
	if (info.signature) {
		sections.push(`Signature:\n${info.signature}`);
	}
	elements.pairOutputMeta.textContent = sections.join("\n\n");
	elements.pairOutputMeta.classList.toggle("hidden", sections.length === 0);
}

function activateNumberTool() {
	numberSyncing = true;
	if (elements.numberBinary) elements.numberBinary.value = "";
	if (elements.numberOctal) elements.numberOctal.value = "";
	if (elements.numberDecimal) elements.numberDecimal.value = "";
	if (elements.numberHex) elements.numberHex.value = "";
	numberSyncing = false;
	setStatus("就緒", false, "ready");
}

function handleNumberInput(base) {
	if (!isNumberTool(currentTool) || numberSyncing) return;
	runNumberConversion(base);
}

function runNumberConversion(base) {
	if (!wasmReady || !elements[`number${capitalize(base)}`]) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const value = elements[`number${capitalize(base)}`].value;
	if (!value.trim()) {
		numberSyncing = true;
		["Binary", "Octal", "Decimal", "Hex"].forEach((key) => {
			if (elements[`number${key}`]) elements[`number${key}`].value = "";
		});
		numberSyncing = false;
		setStatus("已清除");
		return;
	}
	let response;
	try {
		response = window.convertNumberBase(base, value);
	} catch (err) {
		setStatus(err.message, true);
		return;
	}
	if (!response || response.error) {
		setStatus(response?.error || "轉換失敗", true);
		return;
	}
	const result = response.result || {};
	numberSyncing = true;
	if (elements.numberBinary && typeof result.binary === "string") {
		elements.numberBinary.value = result.binary;
	}
	if (elements.numberOctal && typeof result.octal === "string") {
		elements.numberOctal.value = result.octal;
	}
	if (elements.numberDecimal && typeof result.decimal === "string") {
		elements.numberDecimal.value = result.decimal;
	}
	if (elements.numberHex && typeof result.hex === "string") {
		elements.numberHex.value = result.hex;
	}
	numberSyncing = false;
	setStatus("完成", false, "ready");
}

function activateIPv4Tool() {
	if (elements.ipv4Results) {
		elements.ipv4Results.innerHTML =
			'<div class="muted">輸入 IPv4 或 CIDR 以顯示資訊</div>';
	}
	if (elements.ipv4Input) {
		elements.ipv4Input.value = "";
	}
	setStatus("就緒", false, "ready");
}

function runIPv4Conversion() {
	if (!isIPv4Tool(currentTool)) return;
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const value = elements.ipv4Input ? elements.ipv4Input.value.trim() : "";
	if (!value) {
		if (elements.ipv4Results) {
			elements.ipv4Results.innerHTML =
				'<div class="muted">輸入 IPv4 或 CIDR 以顯示資訊</div>';
		}
		setStatus("已清除");
		return;
	}
	let response;
	try {
		response = window.ipv4Info(value);
	} catch (err) {
		setStatus(err.message, true);
		return;
	}
	if (!response || response.error) {
		setStatus(response?.error || "解析失敗", true);
		return;
	}
	renderIPv4Results(response.result || {});
	setStatus("完成", false, "ready");
}

function renderIPv4Results(data) {
	if (!elements.ipv4Results) return;
	const stats = [];
	if (data.standard) {
		stats.push(renderIPv4Row("Standard", data.standard));
	}
	if (data.cidr) {
		stats.push(renderIPv4Row("CIDR", data.cidr));
	}
	if (data.mask) {
		stats.push(renderIPv4Row("Mask", data.mask));
	}
	if (data.rangeStart || data.rangeEnd) {
		stats.push(
			renderIPv4Row(
				"Range",
				`${data.rangeStart || "?"} → ${data.rangeEnd || "?"}`,
			),
		);
	}
	if (data.total) {
		stats.push(renderIPv4Row("Total IPs", data.total));
	}
	if (data.threePart) {
		stats.push(renderIPv4Row("3-part", data.threePart));
	}
	if (data.twoPart) {
		stats.push(renderIPv4Row("2-part", data.twoPart));
	}
	if (data.integer) {
		stats.push(renderIPv4Row("Integer", data.integer));
	}
	if (!stats.length) {
		elements.ipv4Results.innerHTML =
			'<div class="muted">無法解析輸入內容</div>';
		return;
	}
	elements.ipv4Results.innerHTML = `<div class="ipv4-stats">${stats.join("")}</div>`;
}

function renderIPv4Row(label, value) {
	const safeLabel = escapeHTML(label || "");
	const safeValue = escapeHTML(value || "");
	return `
    <div class="stat">
      <span>${safeLabel}</span>
      <span>${safeValue}</span>
    </div>
  `;
}

function activateGeneratorTool() {
	uuidUppercase = false;
	if (elements.uuidToggleCase) {
		elements.uuidToggleCase.dataset.upper = "false";
	}
	refreshUUIDs(true);
	setStatus("就緒", false, "ready");
}

function refreshUUIDs(force = false) {
	if (!isGeneratorTool(currentTool)) return;
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	if (!force && currentUUIDs && Object.keys(currentUUIDs).length > 0) {
		refreshUUIDDisplay();
		return;
	}
	try {
		const response = window.generateUUIDs();
		if (!response) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (response.error) {
			setStatus(`⚠️ ${response.error}`, true);
			return;
		}
		currentUUIDs = response.result || {};
		refreshUUIDDisplay();
		setStatus("已產生新的 UUID", false, "ready");
	} catch (err) {
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function refreshUUIDDisplay() {
	if (!elements.uuidList) return;
	if (!currentUUIDs || Object.keys(currentUUIDs).length === 0) {
		elements.uuidList.innerHTML =
			'<div class="muted">尚未產生任何 UUID</div>';
		return;
	}
	const seen = new Set();
	const entries = [];
	uuidDisplayOrder.forEach((key) => {
		if (currentUUIDs[key]) {
			entries.push([key, currentUUIDs[key]]);
			seen.add(key);
		}
	});
	Object.keys(currentUUIDs).forEach((key) => {
		if (!seen.has(key)) {
			entries.push([key, currentUUIDs[key]]);
		}
	});
	const rows = entries
		.map(([version, value]) => {
			const display = uuidUppercase ? value.toUpperCase() : value.toLowerCase();
			const safeValue = escapeHTML(display);
			const label =
				uuidDisplayLabels[version] || version.toUpperCase();
			return `
        <div class="uuid-row">
          <span>${label}</span>
          <code>${safeValue}</code>
          <button type="button" data-value="${escapeAttr(display)}" data-label="${label}" class="uuid-copy">Copy</button>
        </div>
      `;
		})
		.join("");
	elements.uuidList.innerHTML = rows;
	elements.uuidList.querySelectorAll(".uuid-copy").forEach((btn) => {
		btn.addEventListener("click", () => {
			const value = btn.dataset.value || "";
			if (!value) return;
			navigator.clipboard.writeText(value).then(
				() => setStatus(`已複製 ${btn.dataset.label}`, false, "ready"),
				() => setStatus("無法存取剪貼簿", true),
			);
		});
	});
}

function selectTool(toolId) {
	if (!toolInfo[toolId]) return;
	currentTool = toolId;
	const meta = toolInfo[toolId];
	elements.toolName.textContent = meta.label;
	elements.toolDesc.textContent = meta.description || "";
	const isFormat = toolId === "format";
	const isCoderMain = isCoderMainTool(toolId);
	const isPair = isPairToolId(toolId);
	const isNumber = isNumberTool(toolId);
	const isIPv4 = isIPv4Tool(toolId);
	const isGenerator = isGeneratorTool(toolId);
	if (!isPair) {
		currentPairTool = null;
		updatePairMeta(null);
	}
	document.body.classList.toggle("tool-format", isFormat);
	document.body.classList.toggle("tool-coder", isCoderMain);
	document.body.classList.toggle("tool-pair", isPair);
	document.body.classList.toggle("tool-number", isNumber);
	document.body.classList.toggle("tool-ipv4", isIPv4);
	document.body.classList.toggle("tool-generator", isGenerator);
	elements.converterWorkspace.classList.toggle("hidden", !isFormat);
	if (elements.coderWorkspace) {
		elements.coderWorkspace.classList.toggle("hidden", !isCoderMain);
	}
	if (elements.pairWorkspace) {
		elements.pairWorkspace.classList.toggle("hidden", !isPair);
	}
	if (elements.numberWorkspace) {
		elements.numberWorkspace.classList.toggle("hidden", !isNumber);
	}
	if (elements.ipv4Workspace) {
		elements.ipv4Workspace.classList.toggle("hidden", !isIPv4);
	}
	if (elements.generatorWorkspace) {
		elements.generatorWorkspace.classList.toggle("hidden", !isGenerator);
	}
	updateToolButtons();
	if (isFormat) {
		ensureMode();
		scheduleConvert(true);
		return;
	}
	if (isCoderMain) {
		const nextMode = coderToolModes[toolId] || "encode";
		const changed = coderMode !== nextMode;
		coderMode = nextMode;
		updateCoderTexts();
		if (changed) {
			renderCoderEmpty();
		}
		scheduleCoder(true);
		return;
	}
	if (isPair) {
		activatePairTool(toolId);
	}
	if (isNumber) {
		activateNumberTool();
		return;
	}
	if (isIPv4) {
		activateIPv4Tool();
		return;
	}
	if (isGenerator) {
		activateGeneratorTool();
		return;
	}
}

function updateToolButtons() {
	document
		.querySelectorAll("#toolGroups button")
		.forEach((btn) =>
			btn.classList.toggle("active", btn.dataset.toolId === currentTool),
		);
}

function onSwap() {
	if (currentTool !== "format") return;
	const from = elements.from.value;
	const to = elements.to.value;
	elements.from.value = to;
	elements.to.value = from;
	const oldInput = elements.input.value;
	elements.input.value = elements.output.value;
	elements.output.value = oldInput;
	ensureMode();
}

function ensureMode() {
	if (currentTool !== "format") return false;
	const from = elements.from.value;
	const to = elements.to.value;
	if (!supportedFormats.has(from) || !supportedFormats.has(to)) {
		currentKey = null;
		return false;
	}
	currentKey = `${from}|${to}`;
	elements.inputLabel.textContent = from;
	elements.outputLabel.textContent = to;
	elements.input.placeholder = samples[from] || "";
	scheduleConvert(true);
	return true;
}

function scheduleConvert(immediate = false) {
	if (currentTool !== "format") return;
	if (immediate) {
		convert();
		return;
	}
	clearTimeout(debounceTimer);
	debounceTimer = setTimeout(() => convert(), 250);
}

function scheduleCoder(immediate = false) {
	if (!isCoderMainTool(currentTool)) return;
	if (immediate) {
		runCoder();
		return;
	}
	clearTimeout(coderTimer);
	coderTimer = setTimeout(() => runCoder(), 200);
}

function convert() {
	if (currentTool !== "format") return;
	const from = elements.from.value;
	const to = elements.to.value;
	if (!supportedFormats.has(from) || !supportedFormats.has(to)) {
		setStatus("不支援的格式", true);
		return;
	}
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const raw = elements.input.value;
	if (!raw.trim()) {
		elements.output.value = "";
		setStatus("輸入為空，沒有輸出");
		return;
	}
	try {
		const result = window.transformFormat(from, to, raw);
		if (!result) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (result.error) {
			elements.output.value = "";
			setStatus(`⚠️ ${result.error}`, true);
			return;
		}
		elements.output.value = result.result || "";
		setStatus("完成", false, "ready");
	} catch (err) {
		elements.output.value = "";
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function runCoder() {
	if (!isCoderMainTool(currentTool)) return;
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	const text = elements.coderInput.value || "";
	const trimmed = text.trim();
	if (!trimmed && coderMode !== "hash") {
		renderCoderEmpty();
		return;
	}
	try {
		if (coderMode === "encode") {
			const response = window.encodeContent(text);
			if (!response) {
				setStatus("WASM 尚未載入完成", true);
				return;
			}
			if (response.error) {
				setStatus(`⚠️ ${response.error}`, true);
				return;
			}
			renderEncodeResults(response.result || {});
			setStatus("完成", false, "ready");
			return;
		}
		if (coderMode === "decode") {
			const decoderKey =
				selectedDecoder ||
				(elements.decodeVariant ? elements.decodeVariant.value : "");
			if (!decoderKey) {
				setStatus("請選擇要解碼的編碼", true);
				return;
			}
			const response = window.decodeContent(decoderKey, text);
			if (!response) {
				setStatus("WASM 尚未載入完成", true);
				return;
			}
			if (response.error) {
				setStatus(`⚠️ ${response.error}`, true);
				return;
			}
			const labelInfo = encodingVariantMap.get(decoderKey);
			const displayLabel = labelInfo
				? `${labelInfo.group} · ${labelInfo.label}`
				: "Decoded";
			renderDecodeResult(response.result || "", displayLabel);
			setStatus("完成", false, "ready");
			return;
		}
		const response = window.hashContent(text);
		if (!response) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (response.error) {
			setStatus(`⚠️ ${response.error}`, true);
			return;
		}
		renderHashResults(response.result || {});
		setStatus("完成", false, "ready");
	} catch (err) {
		renderCoderEmpty();
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function copyOutput() {
	if (currentTool !== "format") return;
	const text = elements.output.value;
	if (!text) {
		setStatus("沒有可複製的內容", true);
		return;
	}
	navigator.clipboard.writeText(text).then(
		() => setStatus("已複製到剪貼簿"),
		() => setStatus("無法存取剪貼簿", true),
	);
}

function clearAll() {
	if (isGeneratorTool(currentTool)) {
		uuidUppercase = false;
		if (elements.uuidToggleCase) {
			elements.uuidToggleCase.dataset.upper = "false";
		}
		refreshUUIDs(true);
		return;
	}
	if (isNumberTool(currentTool)) {
		numberSyncing = true;
		if (elements.numberBinary) elements.numberBinary.value = "";
		if (elements.numberOctal) elements.numberOctal.value = "";
		if (elements.numberDecimal) elements.numberDecimal.value = "";
		if (elements.numberHex) elements.numberHex.value = "";
		numberSyncing = false;
		setStatus("已清除");
		return;
	}
	if (isIPv4Tool(currentTool)) {
		if (elements.ipv4Input) elements.ipv4Input.value = "";
		if (elements.ipv4Results) {
			elements.ipv4Results.innerHTML =
				'<div class="muted">輸入 IPv4 或 CIDR 以顯示資訊</div>';
		}
		setStatus("已清除");
		return;
	}
	if (isPairToolId(currentTool)) {
		if (elements.pairInput) elements.pairInput.value = "";
		if (elements.pairOutput) elements.pairOutput.value = "";
		updatePairMeta(null);
		setStatus("已清除");
		return;
	}
	if (isCoderMainTool(currentTool)) {
		elements.coderInput.value = "";
		renderCoderEmpty();
		setStatus("已清除");
		return;
	}
	elements.input.value = "";
	elements.output.value = "";
	setStatus("已清除");
}

function handleHotkeys(e) {
	const mod = e.metaKey || e.ctrlKey;
	if (!mod) return;
	const key = e.key.toLowerCase();
	if (key === "l") {
		e.preventDefault();
		clearAll();
	} else if (key === "enter") {
		e.preventDefault();
		if (currentTool === "format") {
			scheduleConvert(true);
		} else if (isCoderMainTool(currentTool)) {
			scheduleCoder(true);
		} else if (isPairToolId(currentTool)) {
			runPairConversion("input");
		} else if (isGeneratorTool(currentTool)) {
			refreshUUIDs(true);
		}
	}
}

function setStatus(text, isError = false, tone = "") {
	if (!elements.status) return;
	elements.status.textContent = text;
	if (isError) {
		elements.status.dataset.state = "error";
		return;
	}
	elements.status.dataset.state = tone || "";
}

function formatField(target, formatName, minify) {
	if (!wasmReady) {
		setStatus("等待 WebAssembly 載入...", true);
		return;
	}
	if (!supportedFormats.has(formatName)) {
		setStatus("不支援的格式", true);
		return;
	}
	const text = target.value;
	if (!text.trim()) {
		setStatus("沒有可處理的內容", true);
		return;
	}
	try {
		const result = window.formatContent(formatName, text, minify);
		if (!result) {
			setStatus("WASM 尚未載入完成", true);
			return;
		}
		if (result.error) {
			setStatus(`⚠️ ${result.error}`, true);
			return;
		}
		target.value = result.result || "";
		setStatus(minify ? "已壓縮" : "已格式化", false, "ready");
	} catch (err) {
		setStatus(`⚠️ ${err.message}`, true);
	}
}

function escapeHTML(input) {
	return input
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;");
}

function escapeAttr(input) {
	return escapeHTML(input).replace(/"/g, "&quot;");
}

function capitalize(text) {
	if (!text) return "";
	return text.charAt(0).toUpperCase() + text.slice(1);
}

async function loadWasm() {
	setStatus("載入 WebAssembly...");
	try {
		if (!wasmInitPromise) {
			wasmInitPromise = initWasm();
		}
		await wasmInitPromise;
		wasmReady = true;
		setStatus("WebAssembly 就緒，可以開始轉換！", false, "ready");
		if (currentTool === "format" && elements.input.value.trim()) {
			scheduleConvert(true);
		}
		if (isCoderMainTool(currentTool) && elements.coderInput.value.trim()) {
			scheduleCoder(true);
		}
		if (
			isPairToolId(currentTool) &&
			((elements.pairInput && elements.pairInput.value.trim()) ||
				(elements.pairOutput && elements.pairOutput.value.trim()))
		) {
			runPairConversion(pairLastSource);
		}
		if (isNumberTool(currentTool)) {
			runNumberConversion("decimal");
		}
		if (isIPv4Tool(currentTool) && elements.ipv4Input?.value.trim()) {
			runIPv4Conversion();
		}
		if (isGeneratorTool(currentTool)) {
			refreshUUIDs(true);
		}
	} catch (err) {
		console.error(err);
		setStatus(`無法載入 WASM: ${err.message}`, true);
	}
}

async function initWasm() {
	if (typeof WebAssembly === "undefined") {
		throw new Error("瀏覽器不支援 WebAssembly");
	}
	if (typeof Go === "undefined") {
		throw new Error("wasm_exec.js 尚未載入");
	}
	const go = new Go();
	let instance;
	if (WebAssembly.instantiateStreaming) {
		const result = await WebAssembly.instantiateStreaming(
			fetch("app.wasm"),
			go.importObject,
		);
		instance = result.instance;
	} else {
		const response = await fetch("app.wasm");
		const bytes = await response.arrayBuffer();
		const result = await WebAssembly.instantiate(bytes, go.importObject);
		instance = result.instance;
	}
	go.run(instance);
}
